import React, { useState, useEffect } from 'react';
import { 
  View, 
  Text, 
  TextInput, 
  StyleSheet, 
  ScrollView, 
  SafeAreaView,
  ImageBackground,
  Dimensions
} from 'react-native';
import { useTheme } from '@/context/ThemeContext';
import { useLocalSearchParams } from 'expo-router';
import type { BasePageProps, Project } from '@/types/project';
import { GestureDetector, Gesture } from 'react-native-gesture-handler';
import Animated, { useSharedValue, withSpring } from 'react-native-reanimated';

// A4 dimensions at 72dpi (595x842px)
const A4_WIDTH = 595;
const A4_HEIGHT = 842;
const SCREEN_WIDTH = Dimensions.get('window').width;
const SCALE_FACTOR = SCREEN_WIDTH / A4_WIDTH;

// Temporary texture - replace with actual paper textures
const PAPER_TEXTURE = { uri: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAOUlEQVR42u3OMQEAAAQAMJJ7f2g1yCoJ3MzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz8zQMCPwRI1Tj4QwAAAABJRU5ErkJggg==' };

export const CertificatePage: React.FC<BasePageProps> = ({
  isEditing = false,
  onUpdate,
  onToggleEdit,
  onOpenBottomSheet
}) => {
  const { colors } = useTheme();
  const { project } = useLocalSearchParams<{ project: string }>();
  const projectData: Project = project ? JSON.parse(project) : null;
  const [content, setContent] = useState({
    // Data fetched from project details
    projectTitle: projectData?.title || '',
    studentName: projectData?.studentName || 'Jagadish Odedara',
    studentId: projectData?.studentId || '210640107001',
    department: projectData?.department || 'Computer Engineering',
    
    // Data to be generated by AI
    certificateText: '',
    guideName: '',
    hodName: '',
    date: new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })
  });

  // AI generation function
  const generateCertificateContent = async () => {
    try {
      // Call AI service to generate certificate content
      const generatedText = await generateAICertificateText({
        projectTitle: content.projectTitle,
        studentName: content.studentName,
        studentId: content.studentId,
        department: content.department
      });
      
      setContent(prev => ({
        ...prev,
        certificateText: generatedText,
        guideName: generatedText.includes('Prof.') ? 'Prof. XYZ' : 'Dr. ABC',
        hodName: 'Prof. Department Head'
      }));
    } catch (error) {
      console.error('AI generation failed:', error);
    }
  };

  useEffect(() => {
    // Generate initial content when project data loads
    if (projectData && !content.certificateText) {
      generateCertificateContent();
    }
  }, [projectData]);

  const scale = useSharedValue(1);
  const translateX = useSharedValue(0);
  const translateY = useSharedValue(0);

  const pinchGesture = Gesture.Pinch()
    .onUpdate((e) => {
      scale.value = e.scale;
    })
    .onEnd(() => {
      scale.value = withSpring(1);
    });

  const panGesture = Gesture.Pan()
    .onUpdate((e) => {
      translateX.value = e.translationX;
      translateY.value = e.translationY;
    })
    .onEnd(() => {
      translateX.value = withSpring(0);
      translateY.value = withSpring(0);
    });

  const gestures = Gesture.Simultaneous(pinchGesture, panGesture);

  const styles = StyleSheet.create({
    container: {
      flex: 1,
    },
    background: {
      flex: 1,
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 20,
    },
    a4Container: {
      width: A4_WIDTH * SCALE_FACTOR,
      height: A4_HEIGHT * SCALE_FACTOR,
      padding: 20 * SCALE_FACTOR,
      marginTop: -50,
    },
    a4Paper: {
      flex: 1,
      padding: 40 * SCALE_FACTOR,
      borderRadius: 2 * SCALE_FACTOR,
      backgroundColor: colors.surface, // Changed from static color
      shadowColor: colors.shadow || colors.text + '80',
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.2,
      shadowRadius: 10,
      elevation: 10,
      borderWidth: 1,
      borderColor: colors.border + '50',
    },
    header: {
      marginBottom: 30 * SCALE_FACTOR,
      alignItems: 'center',
    },
    university: {
      fontSize: 18,
      fontWeight: '700',
      letterSpacing: 1,
    },
    title: {
      fontSize: 24 * SCALE_FACTOR,
      fontWeight: 'bold',
      textTransform: 'uppercase',
      letterSpacing: 1.5 * SCALE_FACTOR,
    },
    separator: {
      height: 1 * SCALE_FACTOR,
      width: '60%',
      backgroundColor: '#000',
      marginVertical: 15 * SCALE_FACTOR,
    },
    bodyText: {
      fontSize: 14 * SCALE_FACTOR,
      lineHeight: 20 * SCALE_FACTOR,
      textAlign: 'justify',
      marginBottom: 40 * SCALE_FACTOR,
    },
    signatureBlock: {
      marginTop: 50 * SCALE_FACTOR,
      alignItems: 'flex-end',
    },
    signatureLine: {
      flexDirection: 'row',
      marginBottom: 10 * SCALE_FACTOR,
      alignItems: 'baseline',
    },
    label: {
      fontSize: 12 * SCALE_FACTOR,
      marginRight: 8 * SCALE_FACTOR,
    },
    signature: {
      fontSize: 14 * SCALE_FACTOR,
      fontWeight: 'bold',
      textDecorationLine: 'underline',
    },
    date: {
      fontSize: 12 * SCALE_FACTOR,
      marginTop: 20 * SCALE_FACTOR,
    },
    texture: {
      opacity: 0.05,
    },
  });

  return (
    <View style={{ flex: 1, backgroundColor: colors.background, paddingBottom: 60 }}>
      <SafeAreaView style={styles.container}>
        <ImageBackground 
          source={PAPER_TEXTURE} 
          style={[styles.background, { backgroundColor: colors.background }]}
          imageStyle={styles.texture}
        >
          <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', minHeight: Dimensions.get('window').height }}>
            <View style={styles.a4Container}>
              <GestureDetector gesture={gestures}>
                <Animated.View style={[
                  styles.a4Paper,
                  { 
                    transform: [{ scale }, { translateX }, { translateY }],
                    backgroundColor: colors.surface // Theme-aware paper color
                  }
                ]}>
                  <View style={styles.header}>
                    <Text style={[styles.university, { color: colors.text }]}>UNIVERSITY NAME</Text>
                    <Text style={[styles.title, { color: colors.text }]}>CERTIFICATE</Text>
                    <View style={styles.separator} />
                  </View>

                  <Text style={[styles.bodyText, { color: colors.text }]}>
                    {content.certificateText || 
                      'This is to certify that the work contained in this report entitled "[PROJECT TITLE]" has been completed by [STUDENT NAME] ([STUDENT ID]) under my supervision. The work is original and has not been submitted elsewhere.'}
                  </Text>

                  <View style={styles.signatureBlock}>
                    <View style={styles.signatureLine}>
                      <Text style={[styles.label, { color: colors.text }]}>Project Guide:</Text>
                      <Text style={[styles.signature, { color: colors.text }]}>
                      {content.guideName || '[GUIDE NAME]'}
                    </Text>
                    </View>
                    <View style={styles.signatureLine}>
                      <Text style={[styles.label, { color: colors.text }]}>Head of Department:</Text>
                      <Text style={[styles.signature, { color: colors.text }]}>
                      {content.hodName || '[HOD NAME]'}
                    </Text>
                    </View>
                    <Text style={[styles.date, { color: colors.text }]}>
                    {content.date}
                  </Text>
                </View>
              </Animated.View>
            </GestureDetector>
          </View>
        </View>
        </ImageBackground>
      </SafeAreaView>
    </View>
  );
};

// AI Generation Helper
async function generateAICertificateText(details: {
  projectTitle: string;
  studentName: string;
  studentId: string;
  department: string;
}): Promise<string> {
  // This would call your AI service
  return `This is to certify that the work contained in this report entitled "${details.projectTitle}" has been completed by ${details.studentName} (${details.studentId}) from ${details.department} under my supervision. The work is original and has not been submitted elsewhere for any other degree or diploma.`;
}
